package BufferApp;


/**
* BufferApp/Buffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Buffer.idl
* martes 2 de mayo de 2023 12H27' CEST
*/

public interface Buffer extends BufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Buffer
