spring:
  application:
    name: tracksearch
  datasource:
    url: jdbc:postgresql://localhost:5432/tracks
    username: postgres
    password: example
    
server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761
      
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    name: ${spring.application.name}
    description: This application returns a random subject
    version: '@project.version@'
