spring:
  application:
    name: trackinsert
  datasource:
    url: jdbc:postgresql://localhost:5432/tracks
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    
server:
  port: 8084

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761
