version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres 
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tracks
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql